Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,6 +10,22 @@ steps:
   clean: true
 
 - script: |
+    echo "##vso[task.setvariable variable=DocsDirectory]$(Build.ArtifactStagingDirectory)"
+  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+  displayName: 'configure publish for CI'
+
+- script: |
+    echo "##vso[task.setvariable variable=DocsDirectory]$(Build.ArtifactStagingDirectory)/pr/$(System.PullRequest.PullRequestNumber)"
+  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), variables['System.PullRequest.PullRequestNumber']))
+  displayName: 'configure publish for PR'
+
+- script: |
+    echo "##vso[task.logissue type=error]Pipeline only supported for CI or PR builds"
+    exit 1
+  condition: and(succeeded(), eq(variables['DocsDirectory'], ''))
+  displayName: 'fail invalid build'
+
+- script: |
     git config user.email "ron.buckton@microsoft.com"
     git config user.name "Ron Buckton"
   displayName: 'configure git user'
@@ -30,13 +46,13 @@ steps:
 - task: CopyFiles@2
   inputs:
     SourceFolder: docs
-    TargetFolder: $(Build.ArtifactStagingDirectory)
+    TargetFolder: $(DocsDirectory)
     OverWrite: true
   displayName: 'Copy Build Artifacts'
 
 - task: PublishBuildArtifacts@1
   inputs:
-    PathtoPublish: $(Build.ArtifactStagingDirectory)
+    PathToPublish: $(Build.ArtifactStagingDirectory)
     ArtifactName: 'drop'
     publishLocation: 'Container'
   displayName: 'Publish Build Artifacts'
